### ISSUE TITLE
关于conda基础环境的创建问题

### ISSUE THREAD

**Issue by Lucky-xf** [JiangLab2020/P450Diffusion#1]
您好 我目前正在尝试使用您这边提供的yml文件进行创建conda环境时，出现环境创建失败的问题。首先是在yml文件中出现的四个channel中第二个channel "http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge"
该channel是无法访问的，我也单独访问了ustc的云网站，发现现在并没有对应的anaconda的仓库。其次若是删除yml文件中无法访问的channel，则会出现大概有很多ResolvePackageNotFound这样的错误，导致环境的创建失败。
所以我想和您请教一下，有没有最新的yml文件或者能够提供一个新的可以正常下载的conda channel网址

**Comment by AaranWang** [comment]
稍等，我们正在测试环境的适配情况，稍后会提供解决方案。

**Comment by JiangLab2020** [comment]
稍等，我们正在测试环境兼容性，稍后会有解决方案。

**Comment by JiangLab2020** [comment]
我们更新了README，你再按照说明安装一下，应该就可以了

**Comment by Lucky-xf** [comment]
好的 非常感谢您这边提供的解决思路 我这边会再去试试 辛苦您了
